services:
  sensor-simulators:
    image: ghcr.io/bacalhau-project/sensor-log-generator:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/config/config.yaml
      - IDENTITY_FILE=/config/node-identity.json
      # Use DELETE mode for better Docker compatibility (optional - WAL is default)
      # - SENSOR_WAL=false  # Uncomment for Mac/Windows Docker Desktop
    volumes:
      - ./config:/config
      - ./data:/app/data  # Mount local data directory for database persistence
