services:
  sensor-simulators:
    image: ghcr.io/bacalhau-project/sensor-log-generator:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/config/config.yaml
      - IDENTITY_FILE=/config/node-identity.json
    volumes:
      - ./config:/config
      - ./data:/app/data  # Mount local data directory for database persistence
