services:
  sensor-simulator:
    image: ${IMAGE_TAG:-ghcr.io/bacalhau-project/sensor-log-generator:latest}
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      platforms:
      - linux/amd64
      - linux/arm64
      cache_from:
      - type=registry,ref=${CACHE_FROM:-ghcr.io/bacalhau-project/sensor-log-generator:buildcache}
      cache_to:
      - type=registry,ref=${CACHE_TO:-ghcr.io/bacalhau-project/sensor-log-generator:buildcache},mode=max
      labels:
        org.opencontainers.image.title: Sensor Log Generator
        org.opencontainers.image.description: High-performance sensor data simulator
        org.opencontainers.image.version: ${VERSION:-dev}
        org.opencontainers.image.created: ${BUILD_DATE}
        org.opencontainers.image.revision: ${GIT_COMMIT}
      args:
        BUILD_DATE: ${BUILD_DATE}
        VERSION: ${VERSION:-dev}
        GIT_COMMIT: ${GIT_COMMIT}
