# Docker Compose configuration for macOS/Windows Docker Desktop
# Uses DELETE journal mode for proper SQLite sync with host filesystem

services:
  sensor-simulators:
    image: ghcr.io/bacalhau-project/sensor-log-generator:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/config/config.yaml
      - IDENTITY_FILE=/config/node-identity.json
      # DELETE mode is REQUIRED for Docker Desktop on macOS/Windows
      # WAL mode doesn't sync properly with host filesystem
      - SENSOR_WAL=false
    volumes:
      - ./config:/config
      - ./data:/app/data  # Mount local data directory for database persistence
